### ISSUE TITLE
Edit Button Not working (VueJS)

### ISSUE THREAD

**Issue by Harkindey** [Harkindey/Vue-Notes-App#1]
The edit button of the note app , does render a page or option to edit the notes already added.
This is pretty simple so it will on Hacktoberfest

**Comment by Skowt** [comment]
Going to take a stab at this 👀

**Comment by Skowt** [comment]
Fixed and I see someone else also jumped in after my comment.  ¯\_(ツ)_/¯

**Comment by Harkindey** [comment]
Lol @skowt sorry bro.
